:compat-mode:
= Lesson 3: Reaching For The Clouds (Spring Session)

== Introduction
This example shows how you can use Redis as backing store for HTTP session data. Unlike
the standard session, Redis is a service which remains up even if your application is
restarted.

This is particularly important in cloud, because instances can come and go. You can't
rely on standard session implementations. The solution is to handle memory as a service,
bind Redis and use it for session.

== Prerequisites
You will need a https://run.pivotal.io/[Cloud Foundry account] and the
http://docs.cloudfoundry.org/devguide/installcf/[`cf` command line tool] installed. You
will also need a Redis service named `ll-redis-session`:

[source]
----
$ cf create-service rediscloud 30mb ll-redis-session
----

== Testing without Redis
Before showing session data stored in Redis it is helpful to understand how regular
session data works. To do this you can modify the application by commenting out the
Redis dependencies in pom.xml file. You can then try the following:

[source]
----
$ mvn clean package
$ cf push andregs-ll-cloud-session
----

Open a browser to the application and refresh it a few times. You should see the same
UID displayed. Now lets restart the application (keep the browser open):

[source]
----
cf restart andregs-ll-cloud-session
----

If you now refresh the browser again you should see that a new UID is generated. The old
session has gone.

== Testing with Redis
To test with a Redis session restore the dependencies then rebuild and push the app:

[source]
----
$ mvn clean package
$ cf push andregs-ll-cloud-session
----

Repeat the steps above to view the UID in a browser. This time when you restart the
application the session should remain and the same UID will always be displayed. Your
session data is persisted in Redis.
